const styles = {
  container: {
    width: "100%",
    minWidth: "100px",
  },
  carousel: {
    border: "2px solid #ccc",
    overflow: "hidden",
    position: "relative",
    textAlign: "center",
  },
  slider: {
    position: "absolute",
    height: "100%",
    display: "flex",
    transition: "all 0.2s",
  },
  section: {
    flexBasis: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    // overflow: "hidden",
    userSelect: "none",
    draggable: "false",
  },
  left: {
    position: "absolute",
    top: "40%",
    left: "10px",
    cursor: "pointer",
    width: "35px",
    height: "35px",
    textAlign: "center",
    borderRadius: "50%",
    backgroundColor: "#E9EDF0",
    opacity: "0.2",
    transform: "translateY(-50%)",
  },
  arrowleft: {
    border: "solid #555E65",
    borderWidth: "0 3px 3px 0",
    display: "inline-block",
    padding: "3px",
    transform: "rotate(135deg)",
    margin: "35%",
  },

  right: {
    position: "absolute",
    top: "40%",
    right: "10px",
    cursor: "pointer",
    width: "35px",
    height: "35px",
    backgroundColor: "#E9EDF0",
    textAlign: "center",
    borderRadius: "50%",
    opacity: "0.2",
    transform: "translateY(-50%)",
  },
  arrowright: {
    border: "solid #555E65",
    borderWidth: "0 3px 3px 0",
    display: "inline-block",
    padding: "3px",
    transform: "rotate(-45deg)",
    margin: "35%",
  },
  controller: {
    position: "absolute",
    bottom: "10px",
    left: "50%",
    transform: "translate(-50%)",
    listStyle: "none",
    display: "flex",
    padding: "0px",
    margin: "0px",
    flexBasis: "100%",
    width: "100%",
    flexWrap: "Wrap",
    justifyContent: "center",
  },
  controllerButton: {
    width: "8px",
    height: "8px",
    backgroundColor: "#E9EDF0",
    borderRadius: "50px",
    cursor: "pointer",
    margin: "5px",
  },
  selected: {
    background: "transparent",
  },
};

export default styles;
